export const AppImages = {
  IMG_CHALLENGES: require('../assets/images/img_challenges.png'),
  IMG_COMMUNITY: require('../assets/images/img_community.png'),
  IMG_LESSONS: require('../assets/images/img_lessons.png'),
  IMG_LIVE_LIBRARY: require('../assets/images/img_live_library.png'),
  IMG_VIDEO_LESSONS: require('../assets/images/img_video_lessons.png'),
  IMG_SPLASH_BACKGROUND: require('../assets/images/img_splash_background.png'),
  IMG_DIRECTORY_ONE: require('../assets/images/img_directory_one.png'),
  IMG_DIRECTORY_TWO: require('../assets/images/img_directory_two.png'),
  IMG_DIRECTORY_THREE: require('../assets/images/img_directory_three.png'),
  BG_ONE: require('../assets/images/bg_one.png'),
  BG_TWO: require('../assets/images/bg_two.png'),
  BG_THREE: require('../assets/images/bg_three.png'),
  BG_FOUR: require('../assets/images/bg_four.png'),
  BG_FIVE: require('../assets/images/bg_five.png'),
  BG_SIX: require('../assets/images/bg_six.png'),
  PROFILE_ONE: require('../assets/images/profile_one.png'),
  PROFILE_TWO: require('../assets/images/profile_one.png'),
  PROFILE_THREE: require('../assets/images/profile_three.png'),
  PROFILE_FOUR: require('../assets/images/profile_four.png'),
  PROFILE_FIVE: require('../assets/images/profile_five.png'),
  PROFILE_SIX: require('../assets/images/profile_six.png'),
};
